apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    # yaml파일 path
    # 실행 : skaffold dev
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: limkevin1313/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    - image: limkevin1313/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: limkevin1313/event-bus
      context: events-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: limkevin1313/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: limkevin1313/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: limkevin1313/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
